// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/todo-list/[id].ts";
import * as $1 from "./routes/api/todo-list/complete.ts";
import * as $2 from "./routes/api/todo-list/index.ts";
import * as $3 from "./routes/api/todo-list/not-complete.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/TodoList.tsx";

const manifest = {
  routes: {
    "./routes/api/todo-list/[id].ts": $0,
    "./routes/api/todo-list/complete.ts": $1,
    "./routes/api/todo-list/index.ts": $2,
    "./routes/api/todo-list/not-complete.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/TodoList.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
